### PR TITLE
Docker build system 70

### LINKED ISSUE #70: Feature: Docker build system
EVEthing is somewhat difficult to deploy. Modern containerisation can streamline this process by exposing a single container with a complete EVEthing instance inside it.

This container can expose a single web service while containing all the dependencies.

Whenever EVEthing is updated the container can be recreated and re-deployed.

### PR DESCRIPTION
**Pull request by robhaswell**
Fixes https://github.com/madcowfred/evething/issues/70

Dockerfile and configuration for a single-container installation of EVEthing and its dependent stack. Build and execution instructions are located in the README.

### CODE REVIEW

**Comment by Gillingham** [comment]
Would you consider moving this to a fig setup where services like postgresql/redis/nginx are separate instances? We have a bit of a driver to go with that approach for the goonfleet infrastructure. Just haven't gotten around to doing it.

**Comment by robhaswell** [comment]
I was planning to do fig for #72. I think this PR has merit for single-container deployments (Docker hosts typically charge per-container) and I'd like to see it merged. I'll be continuing with #72 after working on some Docker improvements as part of my day job, so you can consider it sponsored development. I think you're looking a 1-3 weeks for that.

(OTOH I do fly for TEST so... :wink:)

**Comment by robhaswell** [comment]
This init system is stupid. I'm replacing it with a real init system.

**Comment by robhaswell** [comment]
Now with not-stupid init system.

**Comment by robhaswell** [comment]
@Gillingham I have this working with `fig` now, sorry it took two months (kek).

Do you want me to nuke this PR and put up a new one with the fig stuff? I think that would be best.

(the fig setup is currently being blocked by https://github.com/madcowfred/evething/issues/88)

**Comment by Gillingham** [comment]
Closing this in favor of re-working on my own. I would much prefer to not use supervisord etc and actually have workers, django, db, etc running in their own containers for scaling vs all in one docker container.

**Pull request closed without merging**
